// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_5vA3w5qCJ0jb-bo1MGFxtjNzV7xNVE',
    appId: '1:196069546209:web:ba37333b0534f5482dffa0',
    messagingSenderId: '196069546209',
    projectId: 'tasklink-fca92',
    authDomain: 'tasklink-fca92.firebaseapp.com',
    storageBucket: 'tasklink-fca92.firebasestorage.app',
    measurementId: 'G-W6PMPN7341',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZpxPlF74w767HZPeFC1vZ3aLTyw46Rg',
    appId: '1:196069546209:android:a01baf1cbf76bc7e2dffa0',
    messagingSenderId: '196069546209',
    projectId: 'tasklink-fca92',
    storageBucket: 'tasklink-fca92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVUFmVb-m-199F72lb92UzO34fJUcJg4',
    appId: '1:196069546209:ios:56892392658c8f6d2dffa0',
    messagingSenderId: '196069546209',
    projectId: 'tasklink-fca92',
    storageBucket: 'tasklink-fca92.firebasestorage.app',
    androidClientId: '196069546209-olvp07l6vglir9u02l0vj7l22annp2l4.apps.googleusercontent.com',
    iosClientId: '196069546209-qfe18gva3uam9a45i4v8r99vftt0r1ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.colaborativeTaskLists',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVUFmVb-m-199F72lb92UzO34fJUcJg4',
    appId: '1:196069546209:ios:56892392658c8f6d2dffa0',
    messagingSenderId: '196069546209',
    projectId: 'tasklink-fca92',
    storageBucket: 'tasklink-fca92.firebasestorage.app',
    androidClientId: '196069546209-olvp07l6vglir9u02l0vj7l22annp2l4.apps.googleusercontent.com',
    iosClientId: '196069546209-qfe18gva3uam9a45i4v8r99vftt0r1ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.colaborativeTaskLists',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_5vA3w5qCJ0jb-bo1MGFxtjNzV7xNVE',
    appId: '1:196069546209:web:afb15fa7b1ac1b6b2dffa0',
    messagingSenderId: '196069546209',
    projectId: 'tasklink-fca92',
    authDomain: 'tasklink-fca92.firebaseapp.com',
    storageBucket: 'tasklink-fca92.firebasestorage.app',
    measurementId: 'G-B8YZ23QVJN',
  );

}